server:
  port: 8088
  servlet:
    context-path: /sd

spring:
  application:
    name: erp
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlserver://101.201.196.17:1433;Databasename=ListingUser   #192.168.0.155
    username: sa
    password: Sd123456   #1996912..
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    druid:
      initial-size: 10
      max-active: 100
      max-wait: 60000
      min-idle: 10
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  auto:
    openurl: true #是否打开，想打开下边就写true
  web:
    loginurl: http://101.201.196.17:8089/sd/official
    ieexcute: C:\\Program Files (x86)\\Internet Explorer\\iexplore.exe
  data:
    mongodb:
      uri: mongodb://admin:123456@101.201.196.17:27017/ListingUser


#  batch:
#    job:
#      enabled: true



mybatis-plus:
  type-enums-package: com.sandu.**
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.sandu.**.vo.**
  configuration:
    map-underscore-to-camel-case: true



thymeleaf:
  prefix: classpath:/templates/  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5


sd:
  config:
    encryption: MD5
    characterEncoding: UTF-8 #编码方式
    operatorID: qilisandu #运营商id
    operatorSecret: AP4Tm1aWpKJph8eA #密钥
    postUrl: http://api.sandu.qd-weimob.com/sandu-api/house/updateHouse #请求的url
    myIp: 101.201.196.17,0   #101.201.196.17
    number: 5

quartz:
  cron1: 0 30 0/1 * * ?
  cron2: 0 30 0/1 * * ?


pagehelper:
  helper-dialect: sqlserver
  reasonable: false
  support-methods-arguments: true
  params: count=countSql


